#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: holmberg.io

# Name of the author
author: Johannes Holmberg

# Folder where Jekyll reads
source: app

# Short bio or description
description: "Johannes Holmberg is a freelance front-end web developer. This is his personal playground with words, design and code."

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-20488297-3

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: http://holmberg.io

# Global media queries
mobile-lg:   'min-width: 34em'
tablet-sm:   'min-width: 45em'
tablet-lg:   'min-width: 57em'
desktop-sm:  'min-width: 67em'
desktop-lg:  'min-width: 84em'
desktop-xl:  'min-width: 118em'

markdown: kramdown
highlighter: pygments
permalink: /:categories/:year/:month/:day/:title/

gems:
  - jekyll-redirect-from

exclude: [
  "node_modules", 
  "gulpfile.js", 
  "package.json", 
  "Gemfile", 
  'bower.json', 
  'app/assets/js/app.dev.js',
  '*.sublime-workspace', 
  '*.sublime-project'
]