# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://holmberg.io
environment: production


# ------------- #
#    Plugins    #
# ------------- #

jekyll-crosspost_to_medium:
  enabled: true
  cache: .cache
