# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://holmberg.io
name: holmberg.io
author: Johannes Holmberg
email: johannes@holmberg.io


# ----------------------- #
#   Global media queries  #
# ----------------------- #

mobile-lg:   'min-width: 34em'
tablet-sm:   'min-width: 45em'
tablet-lg:   'min-width: 57em'
desktop-sm:  'min-width: 67em'
desktop-lg:  'min-width: 84em'
desktop-xl:  'min-width: 118em'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

safe: true

source: ./
destination: _site

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

linenos: true

highlight:
  linenos: true

highlight_options:
  linenos: true

permalink: /:categories/:title/

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

exclude: [
  'node_modules',
  'bower.json',
  'Gemfile',
  'Gemfile.lock',
  'Rakefile',
  'gulpfile.js',
  'package.json'
]


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

google_analytics: UA-20488297-3
